### ISSUE TITLE
User Profile Issues with slug and medium

### ISSUE THREAD

**Issue by fyrepenguin** [factly/kavach#8]

**Comment by deshetti** [comment]
@Bhumi101097 When a user profile is updated, the slug is changing automatically if the display name is changed. The slug should not change after a user is created unless the user modifies it.

@fyrepenguin I am not able to replicate this issue, is this still an issue?

> So, if 'user' is the slug that I have before and I update my profile, it becomes 'user-1' and if I update the profile again, it becomes 'user-1-1' and so on, instead of keeping it just as 'user'
